#!/bin/sh
#!/bin/bash

clear
pacman -Sy --noconfirm
pacman -Sy 
clear

pacmaninit1=$( pacman -Ss glibc  | grep "glibc" 	| grep "installed" | wc -l )
pacmaninit2=$( pacman -Ss dialog | grep "dialog" 	| grep "installed" | wc -l )
pacmaninit3=$( pacman -Ss curl 	 | grep "curl" 		| grep "installed" | wc -l )

if [[ "$pacmaninit1" = "1" && "$pacmaninit2" = "1" && "$pacmaninit3" = "1" ]] ; then
clear
else
clear
sudo pacman -Sy glibc dialog curl ncurses --noconfirm --needed
sleep 5
fi

clear
cd $HOME
curl -LJO https://github.com/krafairus/Arkrat/archive/master.tar.gz
tar -xvf Arkrat-main.tar.gz
cd Arkrat-master

clear
chmod +x *
echo "Cargando Arkrat..."
sleep 2
sh arkrat-install.sh
